# author: 	J. Kraehemann
# created:	03.04.2019

USE MONOSERVICE;

# service config: keep upload 3 days, keep download 7 days, neither scheduled nor delayed upload

SET time_zone='+00:00';

INSERT INTO SERVICE_CONFIG (PROFILE_NAME, UPLOAD_MAX_AGE, DOWNLOAD_MAX_AGE, CLEAN_INTERVAL, SCHEDULED_UPLOAD, UPLOAD_SCHEDULE_TIME, DELAYED_UPLOAD, UPLOAD_DELAY_TIME) VALUES ("default", "1970-01-03 00:00:00", "1970-01-07 00:00:00",  "1970-01-01 01:00:00", false, 0, false, 0);

INSERT INTO ROLES (ROLE_NAME) VALUES ('can_upload');
INSERT INTO ROLES (ROLE_NAME) VALUES ('can_transaction');
INSERT INTO ROLES (ROLE_NAME) VALUES ('can_export');
INSERT INTO ROLES (ROLE_NAME) VALUES ('can_clean');
INSERT INTO ROLES (ROLE_NAME) VALUES ('can_config');

INSERT INTO PRODUCT (PRODUCT_NAME, PRICE) VALUES ("jukebox", 5.00);
INSERT INTO PRODUCT (PRODUCT_NAME, PRICE) VALUES ("diskjokey", 5.00);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin', 'secret');

INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 1);
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 2);
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 3);
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 4);
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 5);
