# author: 	J. Kraehemann
# created:	03.04.2019

USE MONOSERVICE;

INSERT INTO ROLES (ROLE_NAME) VALUES ('can_upload');
INSERT INTO ROLES (ROLE_NAME) VALUES ('can_transaction');

INSERT INTO PRODUCT (PRODUCT_NAME, PRICE) VALUES ("jukebox", 5.00);
INSERT INTO PRODUCT (PRODUCT_NAME, PRICE) VALUES ("diskjokey", 5.00);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin', 'secret');
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 1);
INSERT INTO USERS_ROLES (USERS, ROLES) VALUES (1, 2);
