# author: 	J. Kraehemann
# created:	27.01.2019


DROP DATABASE IF EXISTS MONOSERVICE;


CREATE DATABASE MONOSERVICE DEFAULT CHARACTER SET utf8;


USE MONOSERVICE;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `BILLING_ADDRESS`;


CREATE TABLE `BILLING_ADDRESS`
(
  `BILLING_ADDRESS_ID` INTEGER NOT NULL auto_increment,
  `FIRSTNAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(255),
  `EMAIL` VARCHAR(255),
  `STREET` VARCHAR(255) NOT NULL,
  `ZIP` VARCHAR(255) NOT NULL,
  `CITY` VARCHAR(255) NOT NULL,
  `COUNTRY` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`BILLING_ADDRESS_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `PAYMENT_TRANSACTION`;


CREATE TABLE `PAYMENT_TRANSACTION`
(
  `PAYMENT_TRANSACTION_ID` INTEGER NOT NULL auto_increment,
  `BILLING_ADDRESS` INTEGER,
  `INVOICE_AMOUNT` DECIMAL(15,2),
  `DUE_DATE` TIMESTAMP,
  `COMPLETED` BOOLEAN,
  PRIMARY KEY (`PAYMENT_TRANSACTION_ID`),
  CONSTRAINT PAYMENT_TRANSACTION_REF_BILLING_ADDRESS FOREIGN KEY (BILLING_ADDRESS) REFERENCES BILLING_ADDRESS (BILLING_ADDRESS_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `MEDIA_ACCOUNT`;


CREATE TABLE `MEDIA_ACCOUNT`
(
  `MEDIA_ACCOUNT_ID` INTEGER NOT NULL auto_increment,
  `BILLING_ADDRESS` INTEGER,
  PRIMARY KEY (`MEDIA_ACCOUNT_ID`),
  CONSTRAINT MEDIA_ACCOUNT_REF_BILLING_ADDRESS FOREIGN KEY (BILLING_ADDRESS) REFERENCES BILLING_ADDRESS (BILLING_ADDRESS_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `SESSION_STORE`;


CREATE TABLE `SESSION_STORE`
(
  `SESSION_STORE_ID` INTEGER NOT NULL auto_increment,
  `MEDIA_ACCOUNT` INTEGER,
  `LAST_SEEN` TIMESTAMP,
  `ACTIVE` BOOLEAN,
  `SESSION_ID` VARCHAR(36) NOT NULL,
  `TOKEN` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`SESSION_STORE_ID`),
  CONSTRAINT SESSION_STORE_REF_MEDIA_ACCOUNT FOREIGN KEY (MEDIA_ACCOUNT) REFERENCES MEDIA_ACCOUNT (MEDIA_ACCOUNT_ID),
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `VIDEO_FILE`;


CREATE TABLE `VIDEO_FILE`
(
  `VIDEO_FILE_ID` INTEGER NOT NULL auto_increment,
  `MEDIA_ACCOUNT` INTEGER,
  `RESOURCE_ID` VARCHAR(36) NOT NULL,
  `FILENAME` VARCHAR(255) NOT NULL,
  `DURATION` TIME NOT NULL,
  `PROCESSED` BOOLEAN,
  PRIMARY KEY (`VIDEO_FILE_ID`),
  CONSTRAINT VIDEO_FILE_REF_MEDIA_ACCOUNT FOREIGN KEY (MEDIA_ACCOUNT) REFERENCES MEDIA_ACCOUNT (MEDIA_ACCOUNT_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `RAW_VIDEO_FILE`;


CREATE TABLE `RAW_VIDEO_FILE`
(
  `RAW_VIDEO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`RAW_VIDEO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `RAW_AUDIO_FILE`;


CREATE TABLE `RAW_AUDIO_FILE`
(
  `RAW_AUDIO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`RAW_AUDIO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `TITLE_STRIP_VIDEO_FILE`;


CREATE TABLE `TITLE_STRIP_VIDEO_FILE`
(
  `TITLE_STRIP_VIDEO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `DURATION` TIME NOT NULL,
  PRIMARY KEY (`TITLE_STRIP_VIDEO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `TITLE_STRIP_AUDIO_FILE`;


CREATE TABLE `TITLE_STRIP_AUDIO_FILE`
(
  `TITLE_STRIP_AUDIO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `DURATION` TIME NOT NULL,
  PRIMARY KEY (`TITLE_STRIP_AUDIO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `END_CREDITS_VIDEO_FILE`;


CREATE TABLE `END_CREDITS_VIDEO_FILE`
(
  `END_CREDITS_VIDEO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `DURATION` TIME NOT NULL,
  PRIMARY KEY (`END_CREDITS_VIDEO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `END_CREDITS_AUDIO_FILE`;


CREATE TABLE `END_CREDITS_AUDIO_FILE`
(
  `END_CREDITS_AUDIO_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `DURATION` TIME NOT NULL,
  PRIMARY KEY (`END_CREDITS_AUDIO_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `CAM_UPLOAD_FILE`;


CREATE TABLE `CAM_UPLOAD_FILE`
(
  `CAM_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`CAM_UPLOAD_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `SCREEN_UPLOAD_FILE`;


CREATE TABLE `SCREEN_UPLOAD_FILE`
(
  `SCREEN_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`SCREEN_UPLOAD_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `MIC_UPLOAD_FILE`;


CREATE TABLE `MIC_UPLOAD_FILE`
(
  `MIC_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`MIC_UPLOAD_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `SOUNDCARD_UPLOAD_FILE`;


CREATE TABLE `SOUNDCARD_UPLOAD_FILE`
(
  `SOUNDCARD_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `FILENAME` VARCHAR(255) NOT NULL,
  `CREATION_TIME` TIMESTAMP,
  `DURATION` TIME NOT NULL,
  `AVAILABLE` BOOLEAN,
  PRIMARY KEY (`SOUNDCARD_UPLOAD_FILE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `VIDEO_PROCESSING_QUEUE`;


CREATE TABLE `VIDEO_PROCESSING_QUEUE`
(
  `VIDEO_PROCESSING_QUEUE_ID` INTEGER NOT NULL auto_increment,
  `VIDEO_FILE` INTEGER,
  `RAW_VIDEO_FILE` INTEGER,
  `TITLE_STRIP_VIDEO_FILE` INTEGER,
  `END_CREDITS_VIDEO_FILE` INTEGER,
  `STARTED` BOOLEAN,
  `COMPLETED` BOOLEAN,
  PRIMARY KEY (`VIDEO_PROCESSING_QUEUE_ID`),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_REF_VIDEO_FILE FOREIGN KEY (VIDEO_FILE) REFERENCES VIDEO_FILE (VIDEO_FILE_ID),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_REF_RAW_VIDEO_FILE FOREIGN KEY (RAW_VIDEO_FILE) REFERENCES RAW_VIDEO_FILE (RAW_VIDEO_FILE_ID),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_REF_TITLE_STRIP_VIDEO_FILE FOREIGN KEY (TITLE_STRIP_VIDEO_FILE) REFERENCES TITLE_STRIP_VIDEO_FILE (TITLE_STRIP_VIDEO_FILE_ID),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_REF_END_CREDITS_VIDEO_FILE FOREIGN KEY (END_CREDITS_VIDEO_FILE) REFERENCES END_CREDITS_VIDEO_FILE (END_CREDITS_VIDEO_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE`;


CREATE TABLE `VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE`
(
  `VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `VIDEO_PROCESSING_QUEUE` INTEGER,
  `CAM_UPLOAD_FILE` INTEGER,
  PRIMARY KEY (`VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE_ID`),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE_REF_VIDEO_PROCESSING_QUEUE FOREIGN KEY (VIDEO_PROCESSING_QUEUE) REFERENCES VIDEO_PROCESSING_QUEUE (VIDEO_PROCESSING_QUEUE_ID),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_CAM_UPLOAD_FILE_REF_CAM_UPLOAD_FILE FOREIGN KEY (CAM_UPLOAD_FILE) REFERENCES CAM_UPLOAD_FILE (CAM_UPLOAD_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE`;


CREATE TABLE `VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE`
(
  `VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `VIDEO_PROCESSING_QUEUE` INTEGER,
  `SCREEN_UPLOAD_FILE` INTEGER,
  PRIMARY KEY (`VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE_ID`),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE_REF_VIDEO_PROCESSING_QUEUE FOREIGN KEY (VIDEO_PROCESSING_QUEUE) REFERENCES VIDEO_PROCESSING_QUEUE (VIDEO_PROCESSING_QUEUE_ID),
  CONSTRAINT VIDEO_PROCESSING_QUEUE_SCREEN_UPLOAD_FILE_REF_SCREEN_UPLOAD_FILE FOREIGN KEY (SCREEN_UPLOAD_FILE) REFERENCES SCREEN_UPLOAD_FILE (SCREEN_UPLOAD_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `AUDIO_PROCESSING_QUEUE`;


CREATE TABLE `AUDIO_PROCESSING_QUEUE`
(
  `AUDIO_PROCESSING_QUEUE_ID` INTEGER NOT NULL auto_increment,
  `VIDEO_FILE` INTEGER,
  `RAW_AUDIO_FILE` INTEGER,
  `TITLE_STRIP_AUDIO_FILE` INTEGER,
  `END_CREDITS_AUDIO_FILE` INTEGER,
  `STARTED` BOOLEAN,
  `COMPLETED` BOOLEAN,
  `AVAILABLE_TIME` TIMESTAMP,
  PRIMARY KEY (`AUDIO_PROCESSING_QUEUE_ID`),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_REF_VIDEO_FILE FOREIGN KEY (VIDEO_FILE) REFERENCES VIDEO_FILE (VIDEO_FILE_ID),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_REF_RAW_AUDIO_FILE FOREIGN KEY (RAW_AUDIO_FILE) REFERENCES RAW_AUDIO_FILE (RAW_AUDIO_FILE_ID),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_REF_TITLE_STRIP_AUDIO_FILE FOREIGN KEY (TITLE_STRIP_AUDIO_FILE) REFERENCES TITLE_STRIP_AUDIO_FILE (TITLE_STRIP_AUDIO_FILE_ID),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_REF_END_CREDITS_AUDIO_FILE FOREIGN KEY (END_CREDITS_AUDIO_FILE) REFERENCES END_CREDITS_AUDIO_FILE (END_CREDITS_AUDIO_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE`;


CREATE TABLE `AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE`
(
  `AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `AUDIO_PROCESSING_QUEUE` INTEGER,
  `MIC_UPLOAD_FILE` INTEGER,
  PRIMARY KEY (`AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE_ID`),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE_REF_AUDIO_PROCESSING_QUEUE FOREIGN KEY (AUDIO_PROCESSING_QUEUE) REFERENCES AUDIO_PROCESSING_QUEUE (AUDIO_PROCESSING_QUEUE_ID),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_MIC_UPLOAD_FILE_REF_MIC_UPLOAD_FILE FOREIGN KEY (MIC_UPLOAD_FILE) REFERENCES MIC_UPLOAD_FILE (MIC_UPLOAD_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------

DROP TABLE IF EXISTS `AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE`;


CREATE TABLE `AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE`
(
  `AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE_ID` INTEGER NOT NULL auto_increment,
  `AUDIO_PROCESSING_QUEUE` INTEGER,
  `SOUNDCARD_UPLOAD_FILE` INTEGER,
  PRIMARY KEY (`AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE_ID`),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE_REF_AUDIO_PROCESSING_QUEUE FOREIGN KEY (AUDIO_PROCESSING_QUEUE) REFERENCES AUDIO_PROCESSING_QUEUE (AUDIO_PROCESSING_QUEUE_ID),
  CONSTRAINT AUDIO_PROCESSING_QUEUE_SOUNDCARD_UPLOAD_FILE_REF_SOUNDCARD_UPLOAD_FILE FOREIGN KEY (SOUNDCARD_UPLOAD_FILE) REFERENCES SOUNDCARD_UPLOAD_FILE (SOUNDCARD_UPLOAD_FILE_ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

#----------------------------------------------------------------------------------------
